version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
    networks:
      identityserverui: null


  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    networks:
      identityserverui: null

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/ 
    networks:
      identityserverui: null
  
  sqlServer:
    container_name: sqlServer
    environment:
        SA_PASSWORD: '${DB_PASSWORD:-Password_123}'
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "5555:1433"
    volumes:
      - 'dbdata:/var/opt/mssql'
    networks:
      identityserverui: null

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
      identityserverui: null

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/root/.pgadmin 
    networks:
      identityserverui: null

  portainer:
    container_name: portainer
    restart: always
    ports:
        - "9000:9000"
        - "8080:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      identityserverui: null

  #mongoclient:
  #  image: mongoclient/mongoclient:latest
  #  container_name: mongoclient
  #  hostname: mongoclient
  #  depends_on:
  #    - mongodb
  #  ports:
  #    - 3000:3000

  ############### IDENTITY SERVER ################       
   
  nginx-proxy:
   
     container_name: nginx-proxy
     ports:
      - '80:80'
      - '443:443'
     
      
     volumes:
      #- './shared/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './shared/nginx/vhost.d:/etc/nginx/vhost.d'

     networks:
      proxy: null
      identityserverui:
        aliases:
          - sts.skoruba.local
          - admin.skoruba.local
          - admin-api.skoruba.local
          - web.skoruba.local
          - ocelot.skoruba.local
          - catalog.skoruba.local
          - order.skoruba.local
          - basket.skoruba.local
          - discount.skoruba.local
          - discountgrpc.skoruba.local
          - aggregator.skoruba.local
     restart: always

  identityserver.admin:
    
    container_name: identityserveradmin
    environment:
      - VIRTUAL_HOST=admin.skoruba.local
      #- VIRTUAL_PROTO=https
      #- VIRTUAL_PORT=443
      - 'ConnectionStrings__ConfigurationDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__AdminLogDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.skoruba.local'
      - 'AdminConfiguration__IdentityAdminRedirectUri=https://admin.skoruba.local/signin-oidc'
      - 'AdminConfiguration__IdentityServerBaseUrl=https://sts.skoruba.local'
      - AdminConfiguration__RequireHttpsMetadata=false
      - 'IdentityServerData__Clients__0__ClientUri=https://admin.skoruba.local'
      - 'IdentityServerData__Clients__0__RedirectUris__0=https://admin.skoruba.local/signin-oidc'
      - 'IdentityServerData__Clients__0__FrontChannelLogoutUri=https://admin.skoruba.local/signin-oidc'
      - 'IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://admin.skoruba.local/signout-callback-oidc'
      - 'IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://admin.skoruba.local'
      - 'IdentityServerData__Clients__1__RedirectUris__0=https://admin-api.skoruba.local/swagger/oauth2-redirect.html'
      - 'Serilog__WriteTo__1__Args__connectionString=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'

      - ASPNETCORE_ENVIRONMENT=Development
    command: dotnet Skoruba.IdentityServer4.Admin.dll /seed
    depends_on:
      - sqlServer
      - identityserver.sts.identity
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/identitydata.json:/app/identitydata.json'
      - './shared/identityserverdata.json:/app/identityserverdata.json'

    networks:
      identityserverui: null

  identityserver.admin.api:
   

    container_name: identityserveradminapi
    environment:
      - VIRTUAL_HOST=admin-api.skoruba.local
      #- VIRTUAL_PROTO=https
      #- VIRTUAL_PORT=443
      - AdminApiConfiguration__RequireHttpsMetadata=false
      - 'AdminApiConfiguration__ApiBaseUrl=https://admin-api.skoruba.local'
      - 'AdminApiConfiguration__IdentityServerBaseUrl=https://sts.skoruba.local'
      - 'ConnectionStrings__ConfigurationDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__AdminLogDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'

      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      
    networks:
      identityserverui: null


  identityserver.sts.identity:

    container_name: identityserverstsidentity
    environment:
      - VIRTUAL_HOST=sts.skoruba.local
      #- VIRTUAL_PROTO=https
      #- VIRTUAL_PORT=443      
      - 'ConnectionStrings__ConfigurationDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=sqlServer;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password_123};MultipleActiveResultSets=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.skoruba.local'
      - 'IdentityServerOptions__IssuerUri=https://sts.skoruba.local'
      - IdentityServerOptions__Events__RaiseErrorEvents=true
      - IdentityServerOptions__Events__RaiseInformationEvents=true
      - IdentityServerOptions__Events__RaiseFailureEvents=true
      - IdentityServerOptions__Events__RaiseSuccessEvents=true

      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlServer
    volumes:
      - './shared/serilog.json:/app/serilog.json'

    networks:
      identityserverui:
        aliases:
          - sts.skoruba.local




 


#################################################################

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "IdentityServer:Uri=http://sts.skoruba.local"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"
      - VIRTUAL_HOST=catalog.skoruba.local
    depends_on:
      - catalogdb
      - identityserver.sts.identity
      - apm-server
      - elasticsearch    
        
    networks:
      identityserverui: null

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      
      - "GrpcSettings:DiscountUrl=http://discountgrpc.skoruba.local"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "IdentityServer:Uri=http://sts.skoruba.local"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"
      
      - VIRTUAL_HOST=basket.skoruba.local
     
    depends_on:
      - basketdb
      - rabbitmq
      - identityserver.sts.identity
      - apm-server
      - elasticsearch
   
     
    networks:
       identityserverui: null


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityServer:Uri=http://sts.skoruba.local"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"      
      - VIRTUAL_HOST=discount.skoruba.local
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
        - discountdb
        - apm-server
        - elasticsearch
  
     
    networks:
       identityserverui: null


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityServer:Uri=http://sts.skoruba.local"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"      
      - VIRTUAL_HOST=discountgrpc.skoruba.local      
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
        - discountdb
        - apm-server
        - elasticsearch      
    
     
    networks:
       identityserverui: null

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=sqlServer;Database=orderdb;User Id=sa;Password=${DB_PASSWORD:-Password_123}"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "IdentityServer:Uri=http://sts.skoruba.local"
      
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"
      
      - VIRTUAL_HOST=order.skoruba.local
    depends_on:
      - sqlServer
      - rabbitmq
      - identityserver.sts.identity

      - apm-server
      - elasticsearch
     
    networks:
       identityserverui: null



  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityServer:Uri=http://sts.skoruba.local"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"      
      - VIRTUAL_HOST=ocelot.skoruba.local
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
        - identityserver.sts.identity
        - apm-server
        - elasticsearch  
     
    networks:
       identityserverui: null

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ApiSettings:CatalogUrl=http://catalog.skoruba.local"
        - "ApiSettings:BasketUrl=http://basket.skoruba.local"
        - "ApiSettings:OrderingUrl=http://ordering.skoruba.local"
        - "IdentityServer:Uri=http://sts.skoruba.local"
        - "ElasticConfiguration__Uri=http://elasticsearch:9200"
        - "ElasticApm__ServerUrl=http://apmServer:8200"        
        - VIRTUAL_HOST=aggregator.skoruba.local
        
    depends_on:
        - catalog.api
        - basket.api
        - ordering.api
        - identityserver.sts.identity
        - apm-server
        - elasticsearch   
     
    networks:
     identityserverui: null



  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings__GatewayAddress=http://ocelot.skoruba.local"
      - "IdentityServer__Uri=http://sts.skoruba.local"
      - "IdentityServer__RedirectUri=http://web.skoruba.local/signin-oidc"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "ElasticApm__ServerUrl=http://apmServer:8200"      
      - VIRTUAL_HOST=web.skoruba.local
      #- VIRTUAL_PROTO=http
      #- VIRTUAL_PORT=443
      
        
    depends_on:
        - ocelotapigw
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
        - identityserver.sts.identity
        - apm-server
        - elasticsearch
       
  
     
    networks:
       identityserverui: null
        

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      identityserverui: null

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200:9200
        - 'apm_oss.errorIndices:apm-*'
        - 'apm_oss.spanIndices:apm-*'
        - 'apm_oss.transactionIndices:apm-*'
        - 'apm_oss.onboardingIndices:apm-*'
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 
    networks:
      identityserverui: null


  apm-server:
     container_name: apmServer
     depends_on:
      - elasticsearch
      - kibana
     
     cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
     cap_drop: ["ALL"]
     ports:
     - 8200:8200
     networks:
       identityserverui: null
     command: >
        apm-server -e --strict.perms=false 
         
          -E output.elasticsearch.hosts=["http://elasticsearch:9200:9200"]
     volumes:
        - './apm-server.yml:/usr/share/apm-server/apm-server.yml'

  #webstatus:
  #  container_name: webstatus
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
  #    - HealthChecksUI__HealthChecks__0__Uri=http://catalog.skoruba.local/hc
  #    - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
  #    - HealthChecksUI__HealthChecks__1__Uri=http://basket.skoruba.local/hc
  #    - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
  #    - HealthChecksUI__HealthChecks__2__Uri=http://discount.skoruba.local/hc
  #    - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
  #    - HealthChecksUI__HealthChecks__3__Uri=http://ordering.skoruba.local/hc
  #    - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
  #    - HealthChecksUI__HealthChecks__4__Uri=http://shopping.aggregator/hc
  #    - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
  #    - HealthChecksUI__HealthChecks__5__Uri=http://web.skoruba.local/hc
  #  ports:
  #    - "8007:80"   
  #  networks:
  #    identityserverui: null
    

   
      
##create a SAN cert for both host.docker.internal and localhost
#$cert = New-SelfSignedCertificate -DnsName "host.docker.internal", "localhost" -CertStoreLocation cert:\localmachine\my

##export it for docker container to pick up later
#$password = ConvertTo-SecureString -String "1234" -Force -AsPlainText
#Export-PfxCertificate -Cert $cert -FilePath $env:USERPROFILE\.aspnet\http\aspnetappqsdqwe.pfx -Password $password

## trust it on your host machine
#$store = New-Object System.Security.Cryptography.X509Certificates.X509Store "TrustedPublisher","LocalMachine"
#$store.Open("ReadWrite")
#$store.Add($cert)
#$store.Close()

      #docker run -v $PWD/work -it nginx openssl req -out /work/CSR.csr -new -newkey rsa:2048 -nodes -keyout /work/privateKey.key
