version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/ 
  
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "5555:1433"
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/root/.pgadmin 


  portainer:
    container_name: portainer
    restart: always
    ports:
        - "9000:9000"
        - "8080:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  #mongoclient:
  #  image: mongoclient/mongoclient:latest
  #  container_name: mongoclient
  #  hostname: mongoclient
  #  depends_on:
  #    - mongodb
  #  ports:
  #    - 3000:3000
            
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityServer:Uri=https://identityserver"
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8000 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - catalogdb
      - identityserver
    ports:
      - "8000:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "IdentityServer:Uri=https://identityserver"
      - "GrpcSettings:DiscountUrl=https://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8001 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - basketdb
      - rabbitmq
      - identityserver
    ports:
      - "8001:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8002 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8003 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
      
    ports:
      - "8003:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "IdentityServer:Uri=https://identityserver"
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8004 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - orderdb
      - rabbitmq
      - identityserver
    ports:
      - "8004:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https


  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "IdentityServer:Uri=https://identityserver"
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
        - identityserver
    ports:
      - "8010:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ApiSettings:CatalogUrl=https://catalog.api"
        - "ApiSettings:BasketUrl=https://basket.api"
        - "ApiSettings:OrderingUrl=https://ordering.api"
        
    depends_on:
        - catalog.api
        - basket.api
        - ordering.api
    ports:
        - "8005:80"



  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ApiSettings:GatewayAddress=https://ocelotapigw"
        - "IdentityServer:Uri=https://identityserver"
        - ASPNETCORE_URLS=https://+:443 
        - ASPNETCORE_HTTPS_PORT=8006 
        - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        
    depends_on:
        - ocelotapigw
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
        - identityserver
       
    ports:
        - "8006:443"
    volumes:
        - ${USERPROFILE}\.aspnet\https:/https
        
   
    

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443 
      - ASPNETCORE_HTTPS_PORT=8007 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "ConnectionStrings:DefaultConnection: Server=orderdb;Database=AspIdUsers;User Id=sa;Password=SwN12345678"
    depends_on:
      - orderdb
    ports:
      - "8007:443"
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https


##create a SAN cert for both host.docker.internal and localhost
#$cert = New-SelfSignedCertificate -DnsName "host.docker.internal", "localhost" -CertStoreLocation cert:\localmachine\my

##export it for docker container to pick up later
#$password = ConvertTo-SecureString -String "1234" -Force -AsPlainText
#Export-PfxCertificate -Cert $cert -FilePath $env:USERPROFILE\.aspnet\https\aspnetappqsdqwe.pfx -Password $password

## trust it on your host machine
#$store = New-Object System.Security.Cryptography.X509Certificates.X509Store "TrustedPublisher","LocalMachine"
#$store.Open("ReadWrite")
#$store.Add($cert)
#$store.Close()